export const ICONS = {
	'ion-fitness': 'ion-fitness',
	'ion-fitness-outline': 'ion-fitness-outline',
	'material-symbols-add-rounded': 'material-symbols-add-rounded',
	'material-symbols-alarm-outline-rounded': 'material-symbols-alarm-outline-rounded',
	'material-symbols-alarm-rounded': 'material-symbols-alarm-rounded',
	'material-symbols-home-outline-rounded': 'material-symbols-home-outline-rounded',
	'material-symbols-home-rounded': 'material-symbols-home-rounded',
	'material-symbols-monitor-weight': 'material-symbols-monitor-weight',
	'material-symbols-monitor-weight-outline': 'material-symbols-monitor-weight-outline',
	'material-symbols-motion-photos-paused-outline-rounded': 'material-symbols-motion-photos-paused-outline-rounded',
	'material-symbols-pause-rounded': 'material-symbols-pause-rounded',
	'material-symbols-play-arrow-rounded': 'material-symbols-play-arrow-rounded',
	'material-symbols-remove-rounded': 'material-symbols-remove-rounded',
	'material-symbols-replay-rounded': 'material-symbols-replay-rounded',
	'material-symbols-rotate-right-rounded': 'material-symbols-rotate-right-rounded',
	'material-symbols-skip-next-rounded': 'material-symbols-skip-next-rounded',
	'material-symbols-skip-previous-rounded': 'material-symbols-skip-previous-rounded',
	'material-symbols-stop-rounded': 'material-symbols-stop-rounded',
	'material-symbols-timer-outline-rounded': 'material-symbols-timer-outline-rounded',
	'material-symbols-trending-down-rounded': 'material-symbols-trending-down-rounded',
	'material-symbols-trending-flat-rounded': 'material-symbols-trending-flat-rounded',
	'material-symbols-trending-up-rounded': 'material-symbols-trending-up-rounded',
	'material-symbols-delete-outline-rounded': 'material-symbols-delete-outline-rounded',
	'material-symbols-save-outline-rounded': 'material-symbols-save-outline-rounded',
} as const
